name: Run Tests

on: [push, pull_request]

jobs:
  standard-maven:
    uses: quattor/release/.github/workflows/maven-tests.yaml@main
    with:
      dependencies: perl-Parallel-ForkManager ncm-metaconfig
  standard-pan:
    uses: quattor/release/.github/workflows/pan-template-tests.yaml@main
